In [11]:
from pybkb.bkb import BKB
from pybkb.utils.random import generate_random_bkb_inference, generate_random_bkb_inferences, generate_random_bkb
from pybkb.fusion import fuse

import os
import networkx as nx
import json

In [24]:
bkb_paths = ['../bkbs/fisherman.bkb', 
             '../bkbs/pirate.bkb', 
             '../bkbs/illegal_dumping_ev.bkb', 
             '../bkbs/illegal_fishing_ev.bkb', 
             '../bkbs/tsunami_ev.bkb']

In [25]:
bkfs = [BKB.load(path) for path in bkb_paths]

In [26]:
fused = fuse(bkfs, [1 for _ in range(len(bkfs))], collapse=False)

In [27]:
fused.save('../tests/test_bkb_lib/pirate_scenario_fused.bkb')

In [6]:
rand_bkb.description = 'Random bkb used to test json functionality.'

In [7]:
with open('../tests/test_bkb_lib/test_json.json', 'w') as f_:
    json.dump(rand_bkb.to_dict(), f_, indent=2)

In [8]:
rand_bkb.save('../tests/test_bkb_lib/test_json.bkb')

In [7]:
bkis = generate_random_bkb_inferences(features, 5)

In [8]:
bkis[1].render_nx()

CytoscapeWidget(cytoscape_layout={'name': 'dagre', 'nodeSpacing': 10, 'edgeLengthVal': 10}, cytoscape_style=[{…

In [9]:
for b in bkis:
    b.description = 'Test BKB inference fragment to union.'

In [10]:
for b in bkis:
    b.save(os.path.join('../tests/test_bkb_lib/union_fragments', f'{b.name}.bkb'))

In [11]:
unioned = BKB.union(*bkis)
unioned.render_nx()

CytoscapeWidget(cytoscape_layout={'name': 'dagre', 'nodeSpacing': 10, 'edgeLengthVal': 10}, cytoscape_style=[{…

In [12]:
unioned.save('../tests/test_bkb_lib/test_union.bkb')

In [13]:
s = [1,2,3,4]

In [14]:
s.pop(0)

1

In [15]:
s

[2, 3, 4]

In [16]:
BKB.load('../tests/test_bkb_lib/test_union.bkb')

In [11]:
from pybkb.utils.probability import *
import compress_pickle
import pandas as pd

In [5]:
with open('../data/iris-standard_classification-no_missing_values.dat', 'rb') as f_:
    d = compress_pickle.load(f_, compression='lz4')

In [7]:
data, feature_states, srcs = d

In [9]:
feature_states

[('SepalLength', '< 5.55'),
 ('SepalLength', '5.55 - 6.15'),
 ('SepalLength', '≥ 6.15'),
 ('SepalWidth', '< 2.95'),
 ('SepalWidth', '2.95 - 3.35'),
 ('SepalWidth', '≥ 3.35'),
 ('PetalLength', '< 2.45'),
 ('PetalLength', '2.45 - 4.75'),
 ('PetalLength', '≥ 4.75'),
 ('PetalWidth', '< 0.8'),
 ('PetalWidth', '0.8 - 1.75'),
 ('PetalWidth', '≥ 1.75'),
 ('Class', 'Iris-virginica'),
 ('Class', 'Iris-setosa'),
 ('Class', 'Iris-versicolor')]

In [12]:
df = pd.DataFrame.from_records(data, columns=feature_states)

In [19]:
joint_df = df.value_counts([("SepalLength", "< 5.55"), ("SepalWidth", "< 2.95"), ('PetalLength', '< 2.45')], normalize=True)

In [26]:
joint_prob(data, 0, [3, 6])

(0.013333333333333334,
 {'__ncalls__': 1,
  '__nhashlookups__': 0,
  frozenset({0, 3, 6}): 0.013333333333333334})

In [22]:
joint_df.loc[(1.0, 1.0, 1.0)]

0.013333333333333334

In [27]:
data_test = np.random.randn(100000, 3)

In [55]:
jointProbs, edges = np.histogramdd(data, bins=2)

MemoryError: Unable to allocate 8.00 GiB for an array with shape (1073741824,) and data type int64

In [56]:
data.shape

(150, 15)

In [57]:
jpm = np.array([
    [.1, 0, 0],
    [0.2, 0.3, 0.2],
    [0, 0, .2]
])

In [58]:
jpm

array([[0.1, 0. , 0. ],
       [0.2, 0.3, 0.2],
       [0. , 0. , 0.2]])

In [59]:
P_P = np.sum(jpm, axis=1)

In [60]:
P_P

array([0.1, 0.7, 0.2])

In [64]:
P_XgP = jpm / P_P[:,None]

In [69]:
ih = []
for p_xp, p_xgp in zip(jpm.flatten(), P_XgP.flatten()):
    print(p_xp, p_xgp)
    ih.append(p_xp*np.log2(p_xgp))

0.1 1.0
0.0 0.0
0.0 0.0
0.2 0.28571428571428575
0.3 0.4285714285714286
0.2 0.28571428571428575
0.0 0.0
0.0 0.0
0.2 1.0


/tmp/ipykernel_18334/3097852353.py:4: RuntimeWarning: divide by zero encountered in log2
  ih.append(p_xp*np.log2(p_xgp))
/tmp/ipykernel_18334/3097852353.py:4: RuntimeWarning: invalid value encountered in double_scalars
  ih.append(p_xp*np.log2(p_xgp))


In [70]:
ih

[0.0,
 nan,
 nan,
 -0.3614709844115208,
 -0.36671772640093436,
 -0.3614709844115208,
 nan,
 nan,
 0.0]

In [72]:
np.nansum(ih)

-1.0896596952239759

In [145]:
jpm

array([[0.1, 0. , 0. ],
       [0.2, 0.3, 0.2],
       [0. , 0. , 0.2]])

In [144]:
np.fliplr(jpm)

array([[0. , 0. , 0.1],
       [0.2, 0.3, 0.2],
       [0.2, 0. , 0. ]])

In [75]:
p_x_margin = np.sum(jpm, axis=0)
p_p_margin = np.sum(jpm, axis=1)

In [80]:
p_x_margin

array([0.3, 0.3, 0.4])

In [77]:
p_p_margin

array([0.1, 0.7, 0.2])

In [130]:
mi = []
for j, p_xp_row in enumerate(jpm):
    for i, p_xp in enumerate(p_xp_row):
        mi.append(p_xp * np.log2(p_xp/(p_x_margin[i] * p_p_margin[j])))

/tmp/ipykernel_18334/470820342.py:4: RuntimeWarning: divide by zero encountered in log2
  mi.append(p_xp * np.log2(p_xp/(p_x_margin[i] * p_p_margin[j])))
/tmp/ipykernel_18334/470820342.py:4: RuntimeWarning: invalid value encountered in double_scalars
  mi.append(p_xp * np.log2(p_xp/(p_x_margin[i] * p_p_margin[j])))


In [131]:
np.nansum(mi)

0.48129089923069257

In [139]:
np.expand_dims(p_p_margin, axis=0)

array([[0.1, 0.7, 0.2]])

In [133]:
.2 * np.log2(.2/(.3*.7))

-0.014077865578279572

In [142]:
.17925 / .44751

0.40054970838640475

In [92]:
s = np.random.choice(jpm.size, 10, p=jpm.ravel())

In [143]:
0.17784 + 0.11848 + 0.01573

0.31205000000000005

In [95]:
np.unravel_index(s, jpm.shape)

(array([2, 1, 1, 0, 2, 0, 1, 1, 1, 2]), array([2, 1, 1, 0, 2, 0, 2, 0, 0, 2]))

In [102]:
d = np.vstack(np.unravel_index(s, jpm.shape)).T

In [100]:
import itertools

In [101]:
for p in itertools.product(*[[1,2,3]]):
    print(p)

(1,)
(2,)
(3,)


In [106]:
d.dtype

dtype('int64')

In [107]:
jpm

array([[0.1, 0. , 0. ],
       [0.2, 0.3, 0.2],
       [0. , 0. , 0.2]])

In [114]:
coor = [np.unravel_index(i, jpm.shape) for i in range(jpm.size)]
coor

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [115]:
0.3 * np.log2(0.3 / (0.2 * 0.5))

0.4754887502163468

In [116]:
jpm

array([[0.1, 0. , 0. ],
       [0.2, 0.3, 0.2],
       [0. , 0. , 0.2]])

In [119]:
p_0 = np.sum(jpm, axis=1)
p_0

array([0.1, 0.7, 0.2])

In [121]:
p_1 = np.sum(jpm, axis=0)
p_1

array([0.3, 0.3, 0.4])